support_me-main/config/routes.rb
SupportMe::Application.routes.draw do
  match "logout", to: "sessions#destroy"
  match "login",  to: "sessions#create"

  post "/demo", to: "demo#create", as: "create_demo"

  resources :sessions,  only: [:create, :destroy]
  resources :users,     only: [:create]
  resources :customers, only: [:new, :create]
  resources :messages,  only: [:create, :index]
  resources :demo,      only: [:show]

  root to: "home#show"

  namespace :admin do
    get '/support', to: 'chats#index', as: 'chats'
    resources :chats, only: [:show, :update]
  end

end

support_me-main/app/models/chat.rb
class Chat
  attr_accessor :id,
                :customer_id,
                :status,
                :user_id,
                :created_at,
                :updated_at

  def initialize(params = {})
    @id          = params["id"]
    @customer_id = params["customer_id"]
    @status      = params["status"] || "waiting"
    @user_id     = params["user_id"]
    @created_at  = params["created_at"] ? DateTime.parse(params["created_at"]) : DateTime.now
    @updated_at  = params["update_at"] ? DateTime.parse(params["updated_at"]) : DateTime.now
  end
end

support_me-main/app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :email,
                  :name

  validates :email, presence: true, uniqueness: true, format: { with: /.+@.+\..+/i }
  validates :name,  presence: true, uniqueness: true

  has_many :chats
  has_many :messages, as: :author

end

support_me-main/app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  attr_accessor :id,
                :objectId,
                :name,
                :author_id,
                :author_type,
                :chat_id,
                :content,
                :created_at,
                :updated_at

  def initialize(params = {})
    @id          = params["id"]
    @objectId    = @id
    @name        = message_name( params["author_type"], params["author_id"] )

    @author_id   = params["author_id"]
    @author_type = params["author_type"]

    @chat_id     = params["chat_id"]
    @content     = params["content"]
    @created_at  = params["created_at"] ? DateTime.parse(params["created_at"]) : DateTime.now
    @updated_at  = params["updated_at"] ? DateTime.parse(params["updated_at"]) : DateTime.now
  end

  def message_name(author_type, author_id)
    User.find(author_id).name if author_type == "User"
    Customer.find(author_id).name if author_type == "Customer"
  end

  def id
    return self.objectId
  end

  def persisted?
    !(self.id.nil?)
  end
end

support_me-main/app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :name,
                  :email,
                  :password,
                  :password_confirmation

  validates :name, presence: true              
  validates :email,    presence: true, uniqueness: true, format: { with: /.+@.+\..+/i }
  validates :password, presence: true, confirmation: true, on: :create

  has_many :chats
  has_many :messages, as: :author
end

support_me-main/app/controllers/admin/chats_controller.rb
class Admin::ChatsController < ApplicationController
  def index
    require_login

    service = ChatService.new
    chats = service.fetch_chats

    @waiting_chats = chats.select { |chat| chat.status == 'waiting' }
    @active_chats  = chats.select { |chat| chat.status == 'active' }
  end

  def show
    service    = ChatService.new(params[:id])
    @chat      = service.fetch_chat
    @messsages = service.fetch_messages

    service.update_status('active') if @chat.status == 'waiting'
  end

  def update
    require_login

    service = ChatService.new(params[:id])
    @chat   = service.fetch_chat

    service.update_status('resolved') if @chat.status == 'active'
  end

  private

  def require_customer
    customer ||= Customer.find(id: session[:customer_id])
    redirect_to root_path if customer.nil?
  end
end

support_me-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

support_me-main/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
    @customer = Customer.new
  end

  def create
    customer = Customer.find_or_create_by_name_and_email(params[:customer])

    if customer.save
      session[:customer_id] = customer.id

      service = ChatService.new
      chat    = service.create_chat(customer.id)

      redirect_to admin_chat_path(chat.id)
    else
      redirect_to new_customer_path
    end
  end
end

support_me-main/app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def create
    customer = Customer.find_or_create_by_name_and_email(
                                      name:  'Demo Customer',
                                      email: 'demo_customer@supportme.com'
                                      )

    service = ChatService.new
    chat    = service.create_chat(customer.id)

    redirect_to demo_path(chat.id)
  end

  def show
    service   = ChatService.new(params[:id])
    @chat     = service.fetch_chat
    @messages = service.fetch_messages
  end
end

support_me-main/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if current_user
      redirect_to admin_chats_path
    else
      @user = User.new
      render :show
    end
  end
end

support_me-main/app/controllers/messages_controller.rb
class MessagesController  < ApplicationController
  def create
    service  = ChatService.new(params[:message][:chat_id])
    @message = service.create_message(params)
    @chat_id = @message.chat_id

    respond_to do |format|
      format.js {@message}
    end
  end

  def index
    service   = ChatService.new(params[:chat_id])
    @messages = service.fetch_messages

    respond_to do |format|
      format.json { render :json => @messages }
    end
  end
end

support_me-main/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = login(params[:email], params[:password], params[:remember_me])
    if user
      redirect_to admin_chats_path
    else
      redirect_to root_path, alert: "Email or password was invalid."
    end
  end

  def destroy
    logout
    redirect_to root_path, :notice => "Logged out."
  end
end

support_me-main/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.new(params[:user])

    if user.save
      flash[:notice] = "Your account was created. You can login now."
    else
      flash[:alert]  = "Your account could not be created."
    end

    redirect_to root_url
  end
end

support_me-main/app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_time(input)
    input.strftime("%B %d, %Y - %l:%M %p")
  end

  # def get_author_name_for(message)
  #   return User.find_by_id(message.author_id).name if message.author_type == "User"
  #   return Customer.find_by_id(message.author_id).name if message.author_type == "Customer"
  # end
end

support_me-main/app/helpers/customers_helper.rb
module CustomersHelper
end

support_me-main/app/views/admin/chats/_active_chat.html.erb
<li>
  <%=
      link_to "Chat with #{active_chat.id}",
      admin_chat_path(active_chat.id),
      id: "active_chat_links_#{active_chat.id}",
      remote: true,
      method: :get,
      :'data-chat'=> active_chat.id,
      class: 'support-chat-link active'
  %>
</li>


<script>
// on link click, fire off an ajax request to get the messages for the chat.


</script>

support_me-main/app/views/admin/chats/_chat.html.erb
<div id='inner_chatbox_<%= @chat.id%>' class="admin_chat_box">

  <h4>Chat #<%= @chat.id%></h4>
  <button id="<%= @chat.id %>" class='btn btn-mini resolve_button pull-right resolve_issue'>Resolve</button>

  <hr>

  <div class="admin_chat_content">
    <ul id="chat<%= @chat.id%>" class="chat" >
       <%= render partial: 'messages/message', collection: @messages %>
    </ul>
  </div>

  <hr>

  <div id='chat-input'>
    <%= form_for Message.new, remote: true do |f| %>
      <%= f.hidden_field :chat_id, value: @chat.id %>
      <%= f.hidden_field :author_id, value: current_user.id %>
      <%= f.hidden_field :author_type, value: "User" %>
      <div class="input-append">
        <%= f.text_field :content, id: "appendedInputButton", class: "chat-input" %>
        <%= f.submit "Send", class: "btn btn-success admin_button" %>
      </div>
    <% end %>
  </div>

</div>

<%= subscribe_to admin_chat_path(@chat.id) %>

support_me-main/app/views/admin/chats/_waiting_chat.html.erb
<li>
  <%=
      link_to "Chat with #{waiting_chat.id}",
      admin_chat_path(waiting_chat.id),
      id: "waiting_chat_links_#{waiting_chat.id}",
      remote: true,
      method: :get,
      :'data-chat'=> waiting_chat.id,
      class: 'support-chat-link waiting'
  %>
</li>

support_me-main/app/views/admin/chats/index.html.erb
<div class='dashboard'>
  <div class='support-chat-sidebar pull-left'>
    <h3>Chats</h3>

    <div id='active-chats'>
      <% if @active_chats.count == 0 %>
        <h4>No Active Chats.</h4>
      <% else %>
        <h4 id="<%= @active_chats.count %>" class="active_chats_title">
          Active Chats (<%= @active_chats.count %>)
        </h4>
      <% end %>
      <div class="chats">
        <ul id='active-chats-list'>
          <%= render partial: '/admin/chats/active_chat', collection: @active_chats %>
        </ul>
      </div>
    </div>

    <hr>

    <div id='waiting-chats'>
      <% if @waiting_chats.count == 0 %>
        <h4>No one needs help at the moment.</h4>
      <% else %>
        <h4 id="<%= @waiting_chats.count %>" class="waiting_chats_title">
          Waiting Chats (<%= @waiting_chats.count %>)
        </h4>
      <% end %>
      <div class="chats">
        <ul id='waiting-chats-list'>
          <%= render partial: '/admin/chats/waiting_chat', collection: @waiting_chats %>
        </ul>
      </div>
    </div>
  </div>

  <div class="admin-chats pull-right">
    <% 3.times do |x| %>
      <div id='empty' class="support-chat-window"></div>
    <% end %>
    <br><br>
    <% 3.times do |x| %>
      <div id='empty' class="support-chat-window"></div>
    <% end %>
  </div>

</div>


<script type="text/javascript">
  $(document).ready(function(){
    var active_chats = [];
    <% @active_chats.each do |chat| %>
      active_chats.push("<%= chat.id %>");
    <% end %>

    var getChatMessages = function(chat_id){
      var url = '/messages.json?chat_id=' + chat_id;
      $.getJSON(url, function(data) {
        $.each(data, function(key, val) {

          var name_and_time = "<li><span id='customer-chat-author'>" + val["name"] + "</span> <span id='customer-chat-time'>" + val["created_at"] + "</span></li>";
          var message = '<li>' + val["content"] + '</li>';
          $("#chat" + val["chat_id"]).append(name_and_time).append(message);
        });
        Scroller();
      });
    }

    $.each(active_chats, function(index, value){
      $("#active_chat_links_"+value).trigger('click');
    });

    $.each(active_chats, function(index, value){
      getChatMessages(value);
    });

    Array.prototype.remove = function(x) {
      for(i in this){
          if(this[i].toString() == x.toString()){
              this.splice(i,1)
          }
      }
    }

    Array.prototype.diff = function(a) {
      return this.filter(function(i) {return !(a.indexOf(i) > -1);});
    };

    var checkChatWindowsForVacancy = function(current_chat){
      var open_chats_windows = []
      $(".support-chat-window").each(function(i, obj){
        open_chats_windows.push($(this).attr('id'));
      });
      open_chats_windows.remove("empty");
      open_chats_windows.remove("empty");
      var active_chats = []
      $(".active").each(function(i, obj){
        active_chats.push(($(this).attr('id')).replace("active_chat_links_",""));
      });

      var remaining_active_chats = active_chats.diff(open_chats_windows);

      $.each(remaining_active_chats, function(index, value){
        $("#active_chat_links_"+value).trigger('click');
      });

      $.each(remaining_active_chats, function(index, value){
        getChatMessages(value);
      });


    }

    $(".admin-chats").on('click', ".resolve_issue", function(){
      var chat_id = $(this).attr("id");
      $("#inner_chatbox_"+chat_id).remove();
      $("#active_chat_links_"+chat_id).remove();
      $("#waiting_chat_links_"+chat_id).remove();
      $("#"+chat_id).attr("id", "empty");

      var active_chats_count = parseInt($(".active_chats_title").attr("id"))-1;
      $(".active_chats_title").attr("id", (active_chats_count) );
      $(".active_chats_title").text("Active Chats ("+active_chats_count+")");

      $.ajax({
        url: '/admin/chats/'+chat_id,
        type: 'PUT',
        success: function(data) {
        }
      });

      checkChatWindowsForVacancy(chat_id);
    });

    $(".waiting").click(function(){
      var active_chats_count = parseInt($(".active_chats_title").attr("id"))+1;
      $(".active_chats_title").attr("id", (active_chats_count) );
      $(".active_chats_title").text("Active Chats ("+active_chats_count+")");

      var waiting_chats_count = parseInt($(".waiting_chats_title").attr("id"))-1;
      $(".waiting_chats_title").attr("id", (waiting_chats_count) );
      $(".waiting_chats_title").text("Waiting Chats ("+waiting_chats_count+")");
    });
  });
</script>

support_me-main/app/views/admin/chats/show.html.erb
<div id="customer-chat">
  <p id="customer-chat-time"><%= formatted_time(@chat.created_at)%></p>
  <p id="customer-chat-message">You can start this chat by typing your question below.</p>

  <ul id="chat<%= @chat.id %>" class="chat_box">
    <%= render partial: '/messages/message', collection: @messages %>
  </ul>

  <div id="customer-chat-box">
    <%= form_tag @message, remote: true do %>
      <%= text_field_tag :content, "", class: "chat-input" %>
      <%= hidden_field_tag :chat_id, value: @chat.id %>
      <%= hidden_field_tag :author_id, value: @chat.customer_id %>
      <%= hidden_field_tag :author_type, value: "Customer" %>
    <% end %>
  </div>
</div>

<%= subscribe_to admin_chat_path(@chat) %>

support_me-main/app/views/admin/chats/show.js.erb
var chat_id = "<%= params['id'] %>";

var getChatMessages = function(chat_id){
  var url = '/messages.json?chat_id=' + chat_id;
  $.getJSON(url, function(data) {
    $.each(data, function(key, val) {
      // console.log(val)
      var name_and_time = "<li><span id='customer-chat-author'>" + val["name"] + "</span> <span id='customer-chat-time'>" + val["created_at"] + "</span></li>";
      var message = '<li>' + val["content"] + '</li>';
      $("#chat" + val["chat_id"]).append(name_and_time).append(message);
    });

    // console.log(data);
  });
}

function unplaced(){
  var size = $("#" + chat_id).size();
  if (size === 1){
    return false;
  } else {
    return true;
  }
}

$(".support-chat-window").each(function(i, obj){
  if ($(this).attr('id') === 'empty' && unplaced()) {
    $(this).html("<%= escape_javascript(render :partial => '/admin/chats/chat', :id=> 'data-chat' ) %>");
    $(this).attr({'id': "<%= params['id'] %>"});
  } else {
  }
});


getChatMessages(chat_id);

support_me-main/app/views/customers/new.html.erb
<%= form_for @customer do |f| %>
  <% if @customer.errors.any? %>
    <div class="error_messages">
      <ul>
        <% for message in @customer.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field span3">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field span3">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.submit("Start Chat", class: "btn btn-success span3", id: "customer-submit") %>
  </div>
<% end %>

support_me-main/app/views/demo/show.html.erb
 <div id="chat-show">
  <div id='chatbox'>
    <h1>Demo Chat</h1>

    <ul id="chat<%= @chat.id %>" class="chat">
      <%= render @messages %>
    </ul>

    <div id='chat-input'>

    <%= form_for Message.new, remote: true do |f| %>
      <%= f.text_field :content, class: "chat-input" %>
      <%= f.hidden_field :chat_id, value: @chat.id %>
      <%= f.hidden_field :author_id, value: @chat.customer_id %>
      <%= f.hidden_field :author_type, value: "Customer" %>
      <%= f.submit "Send", class: "btn btn-success pull-right span3" %>
    <% end %>
    </div>
  </div>
</div>

<%= subscribe_to admin_chat_path(@chat.id) %>

support_me-main/app/views/home/_login_form.html.erb
<h3 id="text">Log in</h3>

<%= form_tag sessions_path, class: "form" do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email, params[:email] %>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </div>
  <div class="checkbox">
    <%= check_box_tag :remember_me, 1, params[:remember_me] %>
    <%= label_tag :remember_me %>
  </div>
  <div class="actions"><%= submit_tag "Log in", class: "btn btn-success span5 pull-right" %></div>
<% end %>

support_me-main/app/views/home/_modal.html.erb
<div id="signup-form" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-body">
    <h2 id="modal-header">Create an account</h2>
    <%= form_for user, class:"home-form" do |f| %>
      <% if user.errors.any? %>
        <div class="error_messages">
          <ul>
            <% for message in user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="modal-buttons">
        <%= f.submit("Create account", class: "btn btn-success span5 pull-right") %>
        <a class="pull-right" id="modal-cancel" data-dismiss="modal" aria-hidden="true">Cancel</a>
      </div>
    <% end %>
  </div>
</div>

support_me-main/app/views/home/show.html.erb
<div class="container" id="home">
  <div class="row-fluid">
    <div class="span8">
      <h1 id="home-header">
        SupportMe
      </h1>

      <p id="home-leader">
        The best way to provide live support to your customers in your website.
      </p>

      <p class="home-action">
        <a href="#signup-form" role="button" data-toggle="modal">Sign up</a> or <%= link_to "Try our demo", create_demo_path, method: :post %>
      </p>

      <%= render partial: "modal", locals: { user: @user } %>
    </div>

    <div class="span3" id="login-form">
      <%= render "login_form" %>
    </div>
  </div>
</div>

support_me-main/app/views/layouts/_navbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="brand">
      <%= link_to "SupportMe", root_path, class: "no_decoration" %>
    </div>

    <% if current_user %>
      <p class="user">Logged in as <%= current_user.email %>.
      <%= link_to "Log out", logout_path %></p>
    <% end %>
  </div>
</div>

support_me-main/app/views/layouts/_notices.html.erb
<% if flash.notice %>
  <div class="alert">
    <%= flash.notice %>
  </div>
<% elsif flash.alert %>
  <div class="alert alert-error">
    <%= flash.alert %>
  </div>
<% end %>

support_me-main/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupportMe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://0.0.0.0:9292/faye.js" %>
  <%= csrf_meta_tags %>
</head>
  <body class="<%= params[:controller] %>">
    <div id="container-fluid">

      <%= render "layouts/navbar" %>

      <%= render "layouts/notices" %>

      <%= yield %>
    </div>
  </body>
</html>

support_me-main/app/views/messages/_message.html.erb
<li >
  <span id="customer-chat-author">
    <%= message.name %>
  </span>
  <span id="customer-chat-time">
    <%= formatted_time(message.created_at) %>
  </span>
</li>
<li id="customer-chat-message"><%= auto_link(message.content) %></li>

support_me-main/app/views/messages/create.js.erb
<% publish_to admin_chat_path(@chat_id) do %>
  $("#chat<%= @chat_id %>").append("<%= j render(@message) %>");
  $("#new_message")[0].reset();
  $("body").scrollTop( $("body")[0].scrollHeight );
  Scroller();
<% end %>